# SonarQube configuration for ReciclaYa
sonar.host.url=http://localhost:9000
sonar.token=sqp_1aa7160de6f1b79413b585c0fc8efeb241456b75
sonar.projectKey=recicl_ya
sonar.projectName=ReciclaYa
sonar.projectVersion=1.0

# Source and Test Encoding
sonar.sourceEncoding=UTF-8

# Paths to the source code
sonar.sources=frontend/src,ReciclaYa.Api,ReciclaYa.Application,ReciclaYa.Domain,ReciclaYa.Infrastructure
sonar.tests=frontend/src,frontend/e2e
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,frontend/e2e/**/*

# Files and directories to exclude from the analysis
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/bin/**,**/obj/**,**/out/**,**/.vs/**,**/.vscode/**,frontend/playwright-report/**

# Typescript/Javascript configurations
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
