export type ChatMessageRole = 'assistant' | 'user';
export type ChatMessageType = 'text' | 'product_suggestions' | 'tips' | 'quick_links';
export type ComplexityLevel = 'low' | 'medium' | 'high';
export type MarketPotential = 'low' | 'medium' | 'high';
export type UrgenciaLevel = 'baja' | 'media' | 'alta';
export type ChatMode = 'charla' | 'tarjetas';

export interface ProductSuggestion {
  id: string;
  listingId?: string | null;
  residueInput: string;
  productName: string;
  description: string;
  sectorName: string;
  complexity: ComplexityLevel;
  marketPotential: MarketPotential;
  iconName: string;
  /** Whether this suggestion can generate money */
  monetizable: boolean;
  /** Estimated value string, e.g. "S/0.80 - S/1.20 por kg" */
  estimatedValue: string;
  /** Time until money, e.g. "inmediato", "1-7 días" */
  timeToMoney: string;
  /** Minimum quantity to sell, e.g. "5kg (aprox 150 botellas)" */
  minQuantity: string;
  /** Concrete next step */
  nextStep: string;
  /** Human-readable difficulty description */
  difficulty: string;
  /** Detailed action steps generated by Action Generator */
  action: string;
}

export interface QuickLinks {
  googleMaps?: string;
  facebookMarketplace?: string;
  whatsappInfo?: string;
  localRecyclers?: string[];
}

export interface ChatMessage {
  id: string;
  role: ChatMessageRole;
  content: string;
  createdAt: string;
  type: ChatMessageType;
  suggestions?: readonly ProductSuggestion[];
  quickLinks?: QuickLinks;
  urgencia?: UrgenciaLevel;
}

export interface AssistantChatState {
  readonly messages: readonly ChatMessage[];
  readonly selectedSuggestionId: string | null;
  readonly typing: boolean;
}

