export type ChatMessageRole = 'assistant' | 'user';
export type ChatMessageType = 'text' | 'product_suggestions' | 'tips' | 'quick_links';
export type ComplexityLevel = 'low' | 'medium' | 'high';
export type MarketPotential = 'low' | 'medium' | 'high';
export type UrgenciaLevel = 'baja' | 'media' | 'alta';
export type ChatMode = 'charla' | 'tarjetas';
export type NivelColor = 'verde' | 'amarillo' | 'naranja' | 'rojo';

export interface ProductSuggestion {
  id: string;
  listingId?: string | null;
  residueInput: string;
  productName: string;
  description: string;
  sectorName: string;
  complexity: ComplexityLevel;
  marketPotential: MarketPotential;
  iconName: string;
  /** Whether this suggestion can generate money */
  monetizable: boolean;
  /** Estimated value string, e.g. "S/0.80 - S/1.20 por kg" */
  estimatedValue: string;
  /** Time until money, e.g. "inmediato", "1-7 días" */
  timeToMoney: string;
  /** Minimum quantity to sell, e.g. "5kg (aprox 150 botellas)" */
  minQuantity: string;
  /** Concrete next step */
  nextStep: string;
  /** Human-readable difficulty description */
  difficulty: string;
  /** Detailed action steps generated by Action Generator */
  action: string;

  // ── Legal / Regulation fields (optional, populated by n8n v3) ──
  /** Regulatory level 1-4 based on Peruvian law D.L. 1278 */
  nivelRegulatorio?: number;
  /** Color code for the regulation level badge */
  colorNivel?: NivelColor;
  /** Primary law reference, e.g. "D.S. N° 009-2019-MINAM" */
  leyPrincipal?: string;
  /** Documents required from the seller */
  documentosVendedor?: string[];
  /** Documents required from the buyer */
  documentosComprador?: string[];
  /** Maximum fine reference, e.g. "hasta 840 UIT (~S/4.4 millones)" */
  multaMaximaReferencial?: string;
  /** Supervisory entities, e.g. ["MINAM", "OEFA"] */
  entidadesFiscalizadoras?: string[];
  /** Risk level label: bajo, medio, alto, muy-alto */
  riesgoLegal?: string;
}

export interface QuickLinks {
  googleMaps?: string;
  facebookMarketplace?: string;
  whatsappInfo?: string;
  localRecyclers?: string[];
}

export interface ChatMessage {
  id: string;
  role: ChatMessageRole;
  content: string;
  createdAt: string;
  type: ChatMessageType;
  suggestions?: readonly ProductSuggestion[];
  quickLinks?: QuickLinks;
  urgencia?: UrgenciaLevel;
}

export interface AssistantChatState {
  readonly messages: readonly ChatMessage[];
  readonly selectedSuggestionId: string | null;
  readonly typing: boolean;
}

